[package]
name = "lankuu-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "lankuu_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
lankuu-core = { path = "../../crates/lankuu-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", default-features = false, features = ["wry"] }
tauri-plugin-dialog = "2"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time"] }
webrtc = "0.17.2"
